In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import load_digits

digits=load_digits()


## **Separating the dataset into training and testing datasets**

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

## **Applying Logistic Regression**

In [3]:
lr = LogisticRegression(max_iter=1000).fit(X_train, y_train)
lr.score(X_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9583333333333334

## **Applying SVM**

In [4]:
svm = SVC().fit(X_train, y_train)
svm.score(X_test, y_test)

0.9861111111111112

## **Applying Random Forest Classifier**

In [5]:
rfc = RandomForestClassifier(n_estimators=40).fit(X_train, y_train)
rfc.score(X_test, y_test)

0.975

## **Using K-Fold Cross Validation**

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)

In [7]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [8]:
scores_lr=[]
scores_svm=[]
scores_rfc = []

for train_index, test_index in kf.split(digits.data):
  X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  scores_lr.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
  scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
  scores_rfc.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [9]:
scores_lr

[0.9055555555555556,
 0.9611111111111111,
 0.8777777777777778,
 0.9611111111111111,
 0.9444444444444444,
 0.9611111111111111,
 0.9555555555555556,
 0.9273743016759777,
 0.8938547486033519,
 0.9385474860335196]

In [10]:
scores_svm

[0.9444444444444444,
 1.0,
 0.9333333333333333,
 0.9833333333333333,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9664804469273743,
 0.9497206703910615]

In [11]:
scores_rfc

[0.8833333333333333,
 0.9888888888888889,
 0.9333333333333333,
 0.95,
 0.9444444444444444,
 0.9666666666666667,
 0.9722222222222222,
 0.9832402234636871,
 0.9329608938547486,
 0.9441340782122905]

In [13]:
mean_lr_score = np.mean(scores_lr)
mean_lr_score

0.9326443202979515

In [14]:
mean_svm_score = np.mean(scores_svm)
mean_svm_score

0.9732836747361887

In [15]:
mean_rfc_score = np.mean(scores_rfc)
mean_rfc_score

0.9499224084419614

## **Using sklearn's cross_val_score() method**

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target,cv=10)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.90555556, 0.96111111, 0.87777778, 0.92777778, 0.94444444,
       0.96666667, 0.95      , 0.93854749, 0.87150838, 0.93854749])

In [17]:
cross_val_score(SVC(), digits.data, digits.target, cv=10)

array([0.94444444, 0.98888889, 0.92777778, 0.96666667, 0.98333333,
       0.98888889, 0.98888889, 0.99441341, 0.96089385, 0.95530726])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=10)

array([0.90555556, 0.96666667, 0.91666667, 0.92222222, 0.93888889,
       0.96111111, 0.97222222, 0.97206704, 0.92178771, 0.93296089])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=10)

array([0.89444444, 0.97777778, 0.95555556, 0.92222222, 0.95      ,
       0.97222222, 0.97777778, 0.98324022, 0.92178771, 0.93854749])